version: '3'

tasks:
  build: 
    desc: Build an app
    cmds: 
    - GOFLAGS=-mod=mod go build -o bin/atomatiki.exe main.go

  run:
    desc: Run the app
    cmds: 
    - GOFLAGS=-mod=mod go run main.go
